"""Add nomination_guesses table

Revision ID: 03106b2e46fc
Revises: fb1b022d98ef
Create Date: 2026-04-21 07:22:50.330392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03106b2e46fc'
down_revision: Union[str, Sequence[str], None] = 'fb1b022d98ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nomination_guesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_album_id', sa.Integer(), nullable=False),
    sa.Column('guessing_user_id', sa.Integer(), nullable=False),
    sa.Column('guessed_user_id', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_album_id'], ['group_albums.id'], ),
    sa.ForeignKeyConstraint(['guessed_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guessing_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_album_id', 'guessing_user_id', name='unique_guess_per_user_album')
    )
    op.create_index(op.f('ix_nomination_guesses_id'), 'nomination_guesses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nomination_guesses_id'), table_name='nomination_guesses')
    op.drop_table('nomination_guesses')
    # ### end Alembic commands ###
