"""Add timezone field to group_settings

Revision ID: 1564a8298da2
Revises: 653e63d01894
Create Date: 2026-05-10 20:44:51.527756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1564a8298da2'
down_revision: Union[str, Sequence[str], None] = '653e63d01894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_settings', sa.Column('timezone', sa.String(), server_default='America/New_York', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_settings', 'timezone')
    # ### end Alembic commands ###
