"""Add wikipedia fields to albums

Revision ID: 19600d4c5eda
Revises: 5dbd23a8619a
Create Date: 2026-07-25 08:31:58.957263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19600d4c5eda'
down_revision: Union[str, Sequence[str], None] = '5dbd23a8619a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('wikipedia_url', sa.String(), nullable=True))
    op.add_column('albums', sa.Column('wikipedia_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'wikipedia_checked_at')
    op.drop_column('albums', 'wikipedia_url')
    # ### end Alembic commands ###
