"""add timezone and selection days to group settings

Revision ID: 288dce7268eb
Revises: eb3a5b47ea1b
Create Date: 2026-05-20 16:48:13.134913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '288dce7268eb'
down_revision: Union[str, Sequence[str], None] = 'eb3a5b47ea1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_settings', sa.Column('timezone', sa.String(), server_default='America/New_York', nullable=False))
    op.add_column('group_settings', sa.Column('selection_days', postgresql.ARRAY(sa.Integer()), server_default='{0,1,2,3,4,5,6}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_settings', 'selection_days')
    op.drop_column('group_settings', 'timezone')
    # ### end Alembic commands ###
