"""credit ledger and drop review credit column

Revision ID: 313c125f009d
Revises: c905cb84c70f
Create Date: 2026-07-26 21:47:32.177605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '313c125f009d'
down_revision: Union[str, Sequence[str], None] = 'c905cb84c70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priority_review_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', 'album_id', name='unique_credit_per_group_album')
    )
    op.create_index(op.f('ix_priority_review_credits_id'), 'priority_review_credits', ['id'], unique=False)
    op.drop_constraint(op.f('fk_reviews_priority_credited_group_id'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'priority_credited_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('priority_credited_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_reviews_priority_credited_group_id'), 'reviews', 'groups', ['priority_credited_group_id'], ['id'])
    op.drop_index(op.f('ix_priority_review_credits_id'), table_name='priority_review_credits')
    op.drop_table('priority_review_credits')
    # ### end Alembic commands ###
