"""Add group_recaps and recap_views tables

Revision ID: 343017c7855d
Revises: 313c125f009d
Create Date: 2026-08-05 21:20:01.916098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '343017c7855d'
down_revision: Union[str, Sequence[str], None] = '313c125f009d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_recaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'week_start', name='unique_group_week_recap')
    )
    op.create_index(op.f('ix_group_recaps_group_id'), 'group_recaps', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_recaps_id'), 'group_recaps', ['id'], unique=False)
    op.create_table('recap_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recap_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recap_id'], ['group_recaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recap_id', 'user_id', name='unique_recap_view_per_user')
    )
    op.create_index(op.f('ix_recap_views_id'), 'recap_views', ['id'], unique=False)
    op.create_index(op.f('ix_recap_views_recap_id'), 'recap_views', ['recap_id'], unique=False)
    op.create_index(op.f('ix_recap_views_user_id'), 'recap_views', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recap_views_user_id'), table_name='recap_views')
    op.drop_index(op.f('ix_recap_views_recap_id'), table_name='recap_views')
    op.drop_index(op.f('ix_recap_views_id'), table_name='recap_views')
    op.drop_table('recap_views')
    op.drop_index(op.f('ix_group_recaps_id'), table_name='group_recaps')
    op.drop_index(op.f('ix_group_recaps_group_id'), table_name='group_recaps')
    op.drop_table('group_recaps')
    # ### end Alembic commands ###
