"""Add artist_url to albums

Revision ID: 48166160c107
Revises: d86d75892f39
Create Date: 2026-05-18 18:52:53.072016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48166160c107'
down_revision: Union[str, Sequence[str], None] = 'd86d75892f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('artist_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'artist_url')
    # ### end Alembic commands ###
