"""add guess_user_cap to group_settings

Revision ID: 48b4b779e8a0
Revises: c3e7f2a1b904
Create Date: 2026-05-05 21:29:53.661067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b4b779e8a0'
down_revision: Union[str, Sequence[str], None] = 'c3e7f2a1b904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_settings', sa.Column('guess_user_cap', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_settings', 'guess_user_cap')
    # ### end Alembic commands ###
