"""Add chaos mode to group settings and group albums

Revision ID: 5502aec55d4a
Revises: 48b4b779e8a0
Create Date: 2026-05-05 21:49:28.809562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5502aec55d4a'
down_revision: Union[str, Sequence[str], None] = '48b4b779e8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_albums', sa.Column('is_chaos_selection', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('group_settings', sa.Column('chaos_mode', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('nomination_guesses', 'guessed_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nomination_guesses', 'guessed_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('group_settings', 'chaos_mode')
    op.drop_column('group_albums', 'is_chaos_selection')
    # ### end Alembic commands ###
