"""Add public_spin_draws table

Revision ID: 5dbd23a8619a
Revises: 989bfee34e72
Create Date: 2026-07-24 12:41:43.030756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dbd23a8619a'
down_revision: Union[str, Sequence[str], None] = '989bfee34e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_spin_draws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('album_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_spin_draws_draw_date'), 'public_spin_draws', ['draw_date'], unique=True)
    op.create_index(op.f('ix_public_spin_draws_id'), 'public_spin_draws', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_spin_draws_id'), table_name='public_spin_draws')
    op.drop_index(op.f('ix_public_spin_draws_draw_date'), table_name='public_spin_draws')
    op.drop_table('public_spin_draws')
    # ### end Alembic commands ###
