"""Add display_name to users and daily_nomination_limit to group_settings

Revision ID: 653e63d01894
Revises: d4f1093dcaa2
Create Date: 2026-05-10 17:48:38.369298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653e63d01894'
down_revision: Union[str, Sequence[str], None] = 'd4f1093dcaa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_settings', sa.Column('daily_nomination_limit', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_name')
    op.drop_column('group_settings', 'daily_nomination_limit')
    # ### end Alembic commands ###
