"""Add album_id to notifications

Revision ID: 6dbec0e699bd
Revises: 288dce7268eb
Create Date: 2026-05-25 06:35:52.539785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dbec0e699bd'
down_revision: Union[str, Sequence[str], None] = '288dce7268eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('album_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'albums', ['album_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'album_id')
    # ### end Alembic commands ###
