"""Update table relationships, add GroupAlbums and Reviews tables

Revision ID: 7e3166b6f214
Revises: 0448fa28dc8e
Create Date: 2026-02-03 21:23:03.594703

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "7e3166b6f214"
down_revision: str | Sequence[str] | None = "0448fa28dc8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
