"""add album_deals table and dealer settings

Revision ID: 989bfee34e72
Revises: bb63b7d0d0ef
Create Date: 2026-07-10 11:30:20.132561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989bfee34e72'
down_revision: Union[str, Sequence[str], None] = 'bb63b7d0d0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('dealt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', 'album_id', name='unique_deal_per_user_album')
    )
    op.create_index('ix_album_deals_group_album', 'album_deals', ['group_id', 'album_id'], unique=False)
    op.create_index('ix_album_deals_group_user', 'album_deals', ['group_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_album_deals_id'), 'album_deals', ['id'], unique=False)
    op.add_column('group_settings', sa.Column('dealer_mode', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('group_settings', sa.Column('dealer_rolls_per_day', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_settings', 'dealer_rolls_per_day')
    op.drop_column('group_settings', 'dealer_mode')
    op.drop_index(op.f('ix_album_deals_id'), table_name='album_deals')
    op.drop_index('ix_album_deals_group_user', table_name='album_deals')
    op.drop_index('ix_album_deals_group_album', table_name='album_deals')
    op.drop_table('album_deals')
    # ### end Alembic commands ###
