"""Add apple_music_url to albums table

Revision ID: a1cd4b2c74b9
Revises: b7d99e9bd33f
Create Date: 2026-05-12 12:37:54.563397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1cd4b2c74b9'
down_revision: Union[str, Sequence[str], None] = 'b7d99e9bd33f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('apple_music_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'apple_music_url')
    # ### end Alembic commands ###
