"""add ondelete cascade to group_albums group_id nomination_guesses group_album_id and bot_sources bot_group_id

Revision ID: a9c3071562f0
Revises: c7e4a9f12d83
Create Date: 2026-05-14 11:49:22.038280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c3071562f0'
down_revision: Union[str, Sequence[str], None] = 'c7e4a9f12d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bot_sources_bot_group_id_fkey'), 'bot_sources', type_='foreignkey')
    op.create_foreign_key(None, 'bot_sources', 'groups', ['bot_group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('group_albums_group_id_fkey'), 'group_albums', type_='foreignkey')
    op.create_foreign_key(None, 'group_albums', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('nomination_guesses_group_album_id_fkey'), 'nomination_guesses', type_='foreignkey')
    op.create_foreign_key(None, 'nomination_guesses', 'group_albums', ['group_album_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nomination_guesses', type_='foreignkey')
    op.create_foreign_key(op.f('nomination_guesses_group_album_id_fkey'), 'nomination_guesses', 'group_albums', ['group_album_id'], ['id'])
    op.drop_constraint(None, 'group_albums', type_='foreignkey')
    op.create_foreign_key(op.f('group_albums_group_id_fkey'), 'group_albums', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'bot_sources', type_='foreignkey')
    op.create_foreign_key(op.f('bot_sources_bot_group_id_fkey'), 'bot_sources', 'groups', ['bot_group_id'], ['id'])
    # ### end Alembic commands ###
