"""Add youtube_music_id to albums

Revision ID: b7d99e9bd33f
Revises: 085acf4a4df0
Create Date: 2026-05-12 11:16:48.699504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d99e9bd33f'
down_revision: Union[str, Sequence[str], None] = '085acf4a4df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('youtube_music_id', sa.String(), nullable=True))
    op.drop_column('group_settings', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_settings', sa.Column('timezone', sa.VARCHAR(), server_default=sa.text("'America/New_York'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('albums', 'youtube_music_id')
    # ### end Alembic commands ###
