"""Add catch_up_enabled to group_settings

Revision ID: bb63b7d0d0ef
Revises: 6dbec0e699bd
Create Date: 2026-06-12 18:57:50.903629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb63b7d0d0ef'
down_revision: Union[str, Sequence[str], None] = '6dbec0e699bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_settings', sa.Column('catch_up_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_settings', 'catch_up_enabled')
    # ### end Alembic commands ###
