"""add priority pick participation

Revision ID: c905cb84c70f
Revises: 19600d4c5eda
Create Date: 2026-07-26 21:06:35.741535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c905cb84c70f'
down_revision: Union[str, Sequence[str], None] = '19600d4c5eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('priority_group_album_id', sa.Integer(), nullable=True),
    sa.Column('priority_queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['priority_group_album_id'], ['group_albums.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='unique_participation_per_group')
    )
    op.create_index(op.f('ix_group_participation_id'), 'group_participation', ['id'], unique=False)
    op.add_column('group_settings', sa.Column('priority_pick_threshold', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('priority_credited_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_reviews_priority_credited_group_id', 'reviews', 'groups',
        ['priority_credited_group_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_reviews_priority_credited_group_id', 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'priority_credited_group_id')
    op.drop_column('group_settings', 'priority_pick_threshold')
    op.drop_index(op.f('ix_group_participation_id'), table_name='group_participation')
    op.drop_table('group_participation')
    # ### end Alembic commands ###
