"""add min_role_to_nominate to group_settings

Revision ID: ca348829a56e
Revises: ef7527f43abf
Create Date: 2026-05-08 15:32:57.553574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca348829a56e'
down_revision: Union[str, Sequence[str], None] = 'ef7527f43abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_settings', sa.Column('min_role_to_nominate', sa.String(), server_default='member', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_settings', 'min_role_to_nominate')
    # ### end Alembic commands ###
