"""Add group_invite_links table

Revision ID: d4f1093dcaa2
Revises: ca348829a56e
Create Date: 2026-05-10 07:28:37.787453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f1093dcaa2'
down_revision: Union[str, Sequence[str], None] = 'ca348829a56e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_invite_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id')
    )
    op.create_index(op.f('ix_group_invite_links_id'), 'group_invite_links', ['id'], unique=False)
    op.create_index(op.f('ix_group_invite_links_token'), 'group_invite_links', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_invite_links_token'), table_name='group_invite_links')
    op.drop_index(op.f('ix_group_invite_links_id'), table_name='group_invite_links')
    op.drop_table('group_invite_links')
    # ### end Alembic commands ###
