"""add last_read_message_id to group_members

Revision ID: d80390521d15
Revises: ab35a1e54565
Create Date: 2026-08-16 19:47:48.563440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80390521d15'
down_revision: Union[str, Sequence[str], None] = 'ab35a1e54565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('group_members', sa.Column('last_read_message_id', sa.Integer(), nullable=True))

    # Seed every existing membership at its group's newest message.
    #
    # Unread state did not exist before this migration, so nobody has a genuine
    # backlog of unread messages — leaving the column null would invent one and
    # greet every member with a badge counting the group's entire history on
    # the first deploy. Members of groups with no messages stay null, which
    # reads the same as zero.
    op.execute(
        """
        UPDATE group_members gm
        SET last_read_message_id = (
            SELECT MAX(m.id) FROM messages m WHERE m.group_id = gm.group_id
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_members', 'last_read_message_id')
    # ### end Alembic commands ###
