"""make spotify_album_id nullable on albums

Revision ID: d86d75892f39
Revises: d2cdec741c3e
Create Date: 2026-05-17 21:09:23.822624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd86d75892f39'
down_revision: Union[str, Sequence[str], None] = 'd2cdec741c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('albums', 'spotify_album_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('albums', 'spotify_album_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
