"""add link_reports table

Revision ID: e3c707a1d84b
Revises: d80390521d15
Create Date: 2026-08-21 07:46:20.801803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c707a1d84b'
down_revision: Union[str, Sequence[str], None] = 'd80390521d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('link_field', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('suggested_url', sa.String(), nullable=True),
    sa.Column('suggested_value', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='open', nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_reports_album_id'), 'link_reports', ['album_id'], unique=False)
    op.create_index(op.f('ix_link_reports_id'), 'link_reports', ['id'], unique=False)
    op.create_index('ix_link_reports_status_created', 'link_reports', ['status', 'created_at'], unique=False)
    op.create_index('uq_link_reports_open_per_user', 'link_reports', ['album_id', 'reporter_id', 'link_field'], unique=True, postgresql_where=sa.text("status = 'open'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_link_reports_open_per_user', table_name='link_reports', postgresql_where=sa.text("status = 'open'"))
    op.drop_index('ix_link_reports_status_created', table_name='link_reports')
    op.drop_index(op.f('ix_link_reports_id'), table_name='link_reports')
    op.drop_index(op.f('ix_link_reports_album_id'), table_name='link_reports')
    op.drop_table('link_reports')
    # ### end Alembic commands ###
