"""add is_bot to users and add bot_sources table

Revision ID: ef7527f43abf
Revises: 5502aec55d4a
Create Date: 2026-05-08 11:40:33.797996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7527f43abf'
down_revision: Union[str, Sequence[str], None] = '5502aec55d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bot_user_id', sa.Integer(), nullable=False),
    sa.Column('bot_group_id', sa.Integer(), nullable=False),
    sa.Column('processing_state', sa.JSON(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bot_group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['bot_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('is_bot', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_bot')
    op.drop_table('bot_sources')
    # ### end Alembic commands ###
