"""Add is_public to groups

Revision ID: fb1b022d98ef
Revises: e16f9d8ded90
Create Date: 2026-04-19 22:34:54.042846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb1b022d98ef'
down_revision: Union[str, Sequence[str], None] = 'e16f9d8ded90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('role', sa.String(), server_default='member', nullable=False))
    op.add_column('groups', sa.Column('is_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'is_public')
    op.drop_column('group_members', 'role')
    # ### end Alembic commands ###
